apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: wvbv7lr8i-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-1b40bf0c38.3n6x.p3.openshiftapps.com/rhtap/rhtap-qe:8c2edb6c7f75d8f5a94213af5d0f85ae18c38b88@sha256:b22b2c16bfe85f4e5f606d7585f6dd6437d16c95c5fae1155b0aab29cc0c57f6
        name: container-image  
